### PR TITLE
Merge 'Develop' to 'Master'

### PR DESCRIPTION
**Pull request by davellanedam**
Hello, i was trying to load user lang as in docs, but then realised I installed via composer, so latest changes are not there. Can you please make a new release?

### CODE REVIEW

**Comment by davellanedam** [comment]
Thank you!

**Comment by olivierperez** [comment]
You're welcome. Can I ask what's your project?

**Comment by davellanedam** [comment]
Sure, it's a point of sale software for Colombia, we speak spanish here, but I want it to be in english also.

**Comment by olivierperez** [comment]
Great, I'm happy if o80-i18n can help you.
Don't hesitate to modify yourself the library, and to ask for Pull Request.

_Olivier PEREZ_
_olivier@olivierperez.fr olivier@olivierperez.fr_
_Clé publique PGP http://pgp.olivierperez.fr/olivier@olivierperez.fr_
_06.41.73.15.66_

2016-05-15 16:10 GMT+02:00 davellanedam notifications@github.com:

**Comment by davellanedam** [comment]
Thank you very much for making this available to all. Amazing job you did here!

**Pull request merged**
